version: '3'
services:
  cloud-datastore:
    image: google/cloud-sdk:latest
    command: gcloud beta emulators datastore start --host-port=0.0.0.0:8432 --no-store-on-disk
    ports:
      - 8432:8432
    environment:
      CLOUDSDK_CORE_PROJECT: gdg-devparty

  demo-app:
    build: .
    image: gdg/demo-app
    depends_on:
      - cloud-datastore
    ports:
      - 8080:8080
    environment:
      DATASTORE_EMULATOR_HOST: http://cloud-datastore:8432
      GOOGLE_CLOUD_PROJECT: gdg-devparty
      MICRONAUT_ENVIRONMENTS: dev